const sections = [
  { id: "introduction", title: "Introduction", text: "Sri Aurobindo was a poet, philosopher, yogi and one of the early leaders of India’s freedom movement. Born in Calcutta on 15 August 1872 and educated in England, he returned to India in 1893. His spiritual work came to centre on Integral Yoga: a path seeking not only inner liberation, but the transformation of life by a higher consciousness.", href: "https://www.sriaurobindoashram.org/sriaurobindo/" },
  { id: "life-sketch", title: "Life Sketch", text: "After thirteen years in Baroda, Sri Aurobindo entered the nationalist movement in Bengal. A decisive spiritual experience during his imprisonment in the Alipore case deepened the direction of his life. He settled in Pondicherry in 1910, devoted himself to Yoga and writing, and worked with the Mother from 1914 onward. The Sri Aurobindo Ashram took shape around them in 1926.", href: "/sri-aurobindo/life-sketch", internal: true },
  { id: "on-himself", title: "On Himself", text: "Sri Aurobindo’s autobiographical observations illuminate the inner development behind his public life. They describe a Yoga formed through experience, struggle and discovery rather than a fixed system, and reveal how his poetry—especially Savitri—became a field for spiritual exploration.", href: "https://www.sriaurobindoashram.org/sriaurobindo/on_himself.php" },
  { id: "mother-on", title: "The Mother on Sri Aurobindo", text: "The Mother presents Sri Aurobindo’s work as a preparation for a new step in human evolution. Her recollections point to his vast peace, his pioneering exploration of the supramental consciousness, and the living unity of their spiritual work.", href: "https://www.sriaurobindoashram.org/sriaurobindo/mother_on.php" },
  { id: "writings", title: "Writings", text: "His writings range across philosophy, Yoga, social and political thought, poetry, literary criticism and cultural studies. Major works include The Life Divine, The Synthesis of Yoga, Essays on the Gita and Savitri. Together they offer a many-sided vision of consciousness, evolution and the future of humanity.", href: "https://www.sriaurobindoashram.org/sriaurobindo/writings.php" },
  { id: "translations", title: "Translations", text: "Sri Aurobindo translated and interpreted works from Sanskrit, Bengali, Greek and Latin traditions. His renderings sought to carry not merely literal meaning, but something of the original work’s rhythm, atmosphere and spiritual force.", href: "https://www.sriaurobindoashram.org/sriaurobindo/translations.php" },
];

export default function SriAurobindoPage() {
  return <div className="detail-page biography-page">
    <header className="detail-header"><a className="brand" href="/"><img className="society-logo" src="/society-logo-transparent.png" alt="Sri Aurobindo Society symbol"/><span>Sri Aurobindo Society<small>LUCKNOW · GOMTI NAGAR CENTRE</small></span></a><nav aria-label="Page navigation"><a href="/">Home</a><a href="/#wisdom">e-Library</a><a href="/the-mother">The Mother</a></nav></header>
    <main>
      <section className="biography-hero"><div className="biography-copy"><p className="kicker">A LIFE DIVINE · 1872–1950</p><h1>Sri Aurobindo</h1><p className="lead">A life dedicated to India’s awakening and the evolutionary possibilities of the human spirit.</p></div><figure><img src="https://www.sriaurobindoashram.org/sriaurobindo/images/sa_37.jpg" alt="Portrait of Sri Aurobindo"/><figcaption>Portrait from the Sri Aurobindo Ashram website</figcaption></figure></section>
      <nav className="biography-index" aria-label="Sri Aurobindo page sections">{sections.map((section, i)=><a href={`#${section.id}`} key={section.id}><span>{String(i+1).padStart(2,"0")}</span>{section.title}</a>)}</nav>
      <div className="biography-sections">{sections.map((section, i)=><section id={section.id} key={section.id} className="biography-section"><span className="biography-number">{String(i+1).padStart(2,"0")}</span><div><p className="kicker">SRI AUROBINDO</p><h2>{section.title}</h2><p>{section.text}</p><a href={section.href} {...(section.internal ? {} : {target:"_blank", rel:"noreferrer"})}>{section.internal ? "Explore the illustrated life sketch →" : "Read this section on the official Ashram website ↗"}</a></div></section>)}</div>
      <aside className="biography-source"><p className="kicker">SOURCE NOTE</p><p>These original summaries follow the structure and factual material of the official Sri Aurobindo Ashram pages. Follow the source links for the complete, authoritative texts.</p><a className="button primary" href="https://www.sriaurobindoashram.org/sriaurobindo/" target="_blank" rel="noreferrer">Visit official source ↗</a></aside>
    </main>
    <footer className="detail-footer"><a href="/">← Return to the Lucknow Centre</a><small>Towards a Life Divine</small></footer>
  </div>;
}
