const sections = [
  { id: "introduction", title: "Introduction", paragraphs: ["The Mother was born Mirra Alfassa in Paris on 21 February 1878. She studied at the Académie Julian and became an accomplished artist. Her gifts also extended to music and writing, yet from childhood her deepest concern was the discovery and development of consciousness.", "Her search led her to study occult knowledge in Tlemcen, Algeria, during 1905 and 1906. In Paris she gathered groups of spiritual seekers and shared what she was learning through talks and collective study."] },
  { id: "on-herself", title: "On Herself", paragraphs: ["The Mother’s accounts of her early life describe a spiritual awareness present long before she possessed a language for it. Through disciplined observation, artistic work and inner experience, she sought to make every part of life conscious.", "In 1914 she travelled to Pondicherry and met Sri Aurobindo. She recognised him as the spiritual presence that had guided her inwardly for many years. The First World War required her to return to France after eleven months; she later spent four years in Japan before coming back to Pondicherry in April 1920."] },
  { id: "sri-aurobindo-on", title: "Sri Aurobindo on The Mother", paragraphs: ["Sri Aurobindo regarded the Mother as his spiritual equal and collaborator. Their work was one work: he concentrated on the development of Integral Yoga while she gave its consciousness practical expression in the organisation and daily life of the growing community.", "When the Sri Aurobindo Ashram took form in November 1926, he entrusted its complete material and spiritual charge to her. Under her guidance it developed into a many-sided spiritual community devoted to work, education, physical culture, art and inner growth."] },
  { id: "writings", title: "Writings", paragraphs: ["The Mother’s writings and recorded conversations bring spiritual practice into meditation, education, work, relationships, art and the life of the body. Prayers and Meditations, Questions and Answers and the volumes of Words of the Mother preserve guidance that is at once intimate, exact and practical.", "She founded the Sri Aurobindo International Centre of Education in 1952 and Auroville in 1968, extending the ideals of integral education and human unity into living experiments. She continued guiding the Ashram until she left her body on 17 November 1973."] },
];

export default function MotherPage() {
  return <div className="detail-page biography-page mother-page">
    <header className="detail-header"><a className="brand" href="/"><img className="society-logo" src="/society-logo-transparent.png" alt="Sri Aurobindo Society symbol"/><span>Sri Aurobindo Society<small>LUCKNOW · GOMTI NAGAR CENTRE</small></span></a><nav aria-label="Page navigation"><a href="/">Home</a><a href="/#wisdom">e-Library</a><a href="/sri-aurobindo">Sri Aurobindo</a></nav></header>
    <main>
      <section className="biography-hero"><div className="biography-copy"><p className="kicker">THE MOTHER · 1878–1973</p><h1>The Mother</h1><p className="lead">A life of conscious service, spiritual transformation and tireless work for humanity’s future.</p></div><figure><img src="/the-mother-portrait.jpg" alt="Portrait of the Mother, Mirra Alfassa"/><figcaption>The Mother · Mirra Alfassa</figcaption></figure></section>
      <section className="mother-journey" aria-labelledby="mother-journey-title"><div><p className="kicker">A LIFE IN FOUR MOVEMENTS</p><h2 id="mother-journey-title">From Paris to a work for humanity</h2></div><ol><li><span>1878</span><h3>Paris</h3><p>Born Mirra Alfassa, she developed as an artist, pianist and writer while pursuing an intense inner search.</p></li><li><span>1914</span><h3>Pondicherry</h3><p>She met Sri Aurobindo and immediately recognised the spiritual guide whose presence she had known inwardly.</p></li><li><span>1920–1926</span><h3>The shared work</h3><p>After four years in Japan, she returned permanently. Sri Aurobindo later entrusted the Ashram’s material and spiritual life to her.</p></li><li><span>1952–1968</span><h3>Education and unity</h3><p>She established the International Centre of Education and founded Auroville as an international township dedicated to human unity.</p></li></ol></section>
      <nav className="biography-index" aria-label="The Mother page sections">{sections.map((section, i)=><a href={`#${section.id}`} key={section.id}><span>{String(i+1).padStart(2,"0")}</span>{section.title}</a>)}</nav>
      <div className="biography-sections">{sections.map((section, i)=><section id={section.id} key={section.id} className="biography-section"><span className="biography-number">{String(i+1).padStart(2,"0")}</span><div><p className="kicker">THE MOTHER</p><h2>{section.title}</h2>{section.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}</div></section>)}</div>
      <aside className="biography-source"><p className="kicker">ABOUT THIS PROFILE</p><p>This self-contained profile follows the structure and factual record of the Sri Aurobindo Ashram’s account, presented in original wording within the Lucknow Centre’s visual theme.</p></aside>
    </main>
    <footer className="detail-footer"><a href="/">← Return to the Lucknow Centre</a><small>The Song of Life</small></footer>
  </div>;
}
